# Azure Jekyll Build pipeline

trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: UseRubyVersion@0
    inputs:
      versionSpec: '>= 2.7'

  - script: |
      gem install jekyll bundler
      bundle install --retry=3 --jobs=4
    displayName: 'bundle install'

  - script: |
      bundle install
      bundle exec jekyll build
    displayName: 'jekyll'

  - script: |
      bundle install
      bundle exec jekyll build
      bundle exec htmlproofer ./_site --disable-external --check-favicon --check-html --report-invalid-tags --report-missing-names --report-eof-tags --report-missing-doctype --report-mismatched-tags
    displayName: 'html proofing'

  - task: CopyFiles@2
    displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
    inputs:
      SourceFolder: '_site'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: site
